# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34cf8a96e8ca43f196d937ab9f5aabedb8cd6319b698bab75473d7362926da4e99b5b2fd0b9b82af7364e34f2ffeb22cf78ca2dc64c8f5ab848ab28c235b715

test:
  secret_key_base: f8e89bc4aa1c5685074658481e985b90796fbc03cadf3a7b857e5ab6371340b6f07df29c4ad64a804cc8316a0ed3c77e1f117896324a87fcb84502520c560d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
